### ISSUE TITLE
Some doubts

### ISSUE THREAD

**Issue by luisalrp** [SimonDosda/iviea-admin-backend#1]
Hello,

I was looking for an Strapi Printful Plugin and I found your repo. Sorry if it is an obvious question. It is a template or an Strapi applicaton? How can I try it?

Thanks!
Best, Luis

**Comment by SimonDosda** [comment]
Hi Luis,

Thanks for reaching out, to be honest, I don't exactly remember what is in this repo but what I can tell you is that it is something I abandoned and I don't think it is very interesting to look at it, it's an old version of Strapi, and the printful integration is not working.

Good luck with your project!

Simon
